version: "3.8"
services:
  multitor:
    build: ./Tor/multitor
    platform: linux/arm64
    container_name: multitor
    ports:
      - "16378:16378"
      - "16379:16379"
      - "16380:16380"
    volumes:
      - ./Tor/multitor/templates:/usr/src/app/templates:Z
    environment:
      - TOR_INSTANCES=16
      - PROXY_MODE=custom_lb
      - LB_Top_N_Proxies=3
      - LB_Check_Mode=1
    cap_add:
      - NET_ADMIN
    restart: always

  psiphon:
    image: swarupsengupta2007/psiphon:latest
    platform: linux/arm64
    container_name: psiphon
    depends_on:
      - multitor
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./Tor/psiphon:/config:Z
    ports:
      - "1080:1080"
      - "8080:8080"
    restart: always

  warp:
    build: ./Warp-hiddify
    platform: linux/arm64
    container_name: warp
    ports:
      - "8086:8086"
    restart: always
    command: ["--cfon", "--country", "DE", "--bind", "0.0.0.0:8086"]

  # tvc:
  #   build: ./tvc
  #   platform: linux/arm64
  #   privileged: true
  #   container_name: tvc
  #   ports:
  #     - "2334:2334"
  #     - "6756:6756"
  #   restart: always
